/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MotionGalleryRouteImport } from './routes/motion-gallery'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PolicyEditorRouteRouteImport } from './routes/policy-editor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiV1ProtocolRouteImport } from './routes/api/v1/protocol'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1BootstrapRouteImport } from './routes/api/v1/bootstrap'
import { Route as ApiV1RequestsIndexRouteImport } from './routes/api/v1/requests/index'
import { Route as ApiV1ReceiptsIndexRouteImport } from './routes/api/v1/receipts/index'
import { Route as ApiV1PostageIndexRouteImport } from './routes/api/v1/postage/index'
import { Route as ApiV1ContactsIndexRouteImport } from './routes/api/v1/contacts/index'
import { Route as ApiV1AccountsIndexRouteImport } from './routes/api/v1/accounts/index'
import { Route as ApiV1WalletStatusRouteImport } from './routes/api/v1/wallet/status'
import { Route as ApiV1WalletManagedRouteImport } from './routes/api/v1/wallet/managed'
import { Route as ApiV1SendCoordinateRouteImport } from './routes/api/v1/send/coordinate'
import { Route as ApiV1RelayVersionRouteImport } from './routes/api/v1/relay/version'
import { Route as ApiV1RelayReadinessRouteImport } from './routes/api/v1/relay/readiness'
import { Route as ApiV1RelayMessagesRouteImport } from './routes/api/v1/relay/messages'
import { Route as ApiV1RelayHealthRouteImport } from './routes/api/v1/relay/health'
import { Route as ApiV1ReceiptsMessageIdRouteImport } from './routes/api/v1/receipts/$messageId'
import { Route as ApiV1PostageQuoteRouteImport } from './routes/api/v1/postage/quote'
import { Route as ApiV1PostageMessageIdRouteImport } from './routes/api/v1/postage/$messageId'
import { Route as ApiV1PoliciesEvaluateRouteImport } from './routes/api/v1/policies/evaluate'
import { Route as ApiV1PoliciesOwnerRouteImport } from './routes/api/v1/policies/$owner'
import { Route as ApiV1AttachmentsInitiateRouteImport } from './routes/api/v1/attachments/initiate'
import { Route as ApiV1AttachmentsAttachmentIdRouteImport } from './routes/api/v1/attachments/$attachmentId'
import { Route as ApiV1ReceiptsMessageIdReadRouteImport } from './routes/api/v1/receipts/$messageId/read'
import { Route as ApiV1PostageMessageIdSettleRouteImport } from './routes/api/v1/postage/$messageId/settle'
import { Route as ApiV1PostageMessageIdRefundRouteImport } from './routes/api/v1/postage/$messageId/refund'
import { Route as ApiV1AttachmentsAttachmentIdMetaRouteImport } from './routes/api/v1/attachments/$attachmentId/meta'
import { Route as ApiV1AttachmentsAttachmentIdFinalizeRouteImport } from './routes/api/v1/attachments/$attachmentId/finalize'
import { Route as ApiV1PoliciesOwnerSendersSenderRouteImport } from './routes/api/v1/policies/$owner/senders/$sender'
import { Route as ApiV1AttachmentsAttachmentIdChunksChunkIndexRouteImport } from './routes/api/v1/attachments/$attachmentId/chunks/$chunkIndex'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionGalleryRoute = MotionGalleryRouteImport.update({
  id: '/motion-gallery',
  path: '/motion-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyEditorRouteRoute = PolicyEditorRouteRouteImport.update({
  id: '/policy-editor',
  path: '/policy-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProtocolRoute = ApiV1ProtocolRouteImport.update({
  id: '/api/v1/protocol',
  path: '/api/v1/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BootstrapRoute = ApiV1BootstrapRouteImport.update({
  id: '/api/v1/bootstrap',
  path: '/api/v1/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RequestsIndexRoute = ApiV1RequestsIndexRouteImport.update({
  id: '/api/v1/requests/',
  path: '/api/v1/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReceiptsIndexRoute = ApiV1ReceiptsIndexRouteImport.update({
  id: '/api/v1/receipts/',
  path: '/api/v1/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageIndexRoute = ApiV1PostageIndexRouteImport.update({
  id: '/api/v1/postage/',
  path: '/api/v1/postage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactsIndexRoute = ApiV1ContactsIndexRouteImport.update({
  id: '/api/v1/contacts/',
  path: '/api/v1/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsIndexRoute = ApiV1AccountsIndexRouteImport.update({
  id: '/api/v1/accounts/',
  path: '/api/v1/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletStatusRoute = ApiV1WalletStatusRouteImport.update({
  id: '/api/v1/wallet/status',
  path: '/api/v1/wallet/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletManagedRoute = ApiV1WalletManagedRouteImport.update({
  id: '/api/v1/wallet/managed',
  path: '/api/v1/wallet/managed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SendCoordinateRoute = ApiV1SendCoordinateRouteImport.update({
  id: '/api/v1/send/coordinate',
  path: '/api/v1/send/coordinate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayVersionRoute = ApiV1RelayVersionRouteImport.update({
  id: '/api/v1/relay/version',
  path: '/api/v1/relay/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayReadinessRoute = ApiV1RelayReadinessRouteImport.update({
  id: '/api/v1/relay/readiness',
  path: '/api/v1/relay/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayMessagesRoute = ApiV1RelayMessagesRouteImport.update({
  id: '/api/v1/relay/messages',
  path: '/api/v1/relay/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayHealthRoute = ApiV1RelayHealthRouteImport.update({
  id: '/api/v1/relay/health',
  path: '/api/v1/relay/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReceiptsMessageIdRoute = ApiV1ReceiptsMessageIdRouteImport.update({
  id: '/api/v1/receipts/$messageId',
  path: '/api/v1/receipts/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageQuoteRoute = ApiV1PostageQuoteRouteImport.update({
  id: '/api/v1/postage/quote',
  path: '/api/v1/postage/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageMessageIdRoute = ApiV1PostageMessageIdRouteImport.update({
  id: '/api/v1/postage/$messageId',
  path: '/api/v1/postage/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesEvaluateRoute = ApiV1PoliciesEvaluateRouteImport.update({
  id: '/api/v1/policies/evaluate',
  path: '/api/v1/policies/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesOwnerRoute = ApiV1PoliciesOwnerRouteImport.update({
  id: '/api/v1/policies/$owner',
  path: '/api/v1/policies/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AttachmentsInitiateRoute =
  ApiV1AttachmentsInitiateRouteImport.update({
    id: '/api/v1/attachments/initiate',
    path: '/api/v1/attachments/initiate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AttachmentsAttachmentIdRoute =
  ApiV1AttachmentsAttachmentIdRouteImport.update({
    id: '/api/v1/attachments/$attachmentId',
    path: '/api/v1/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReceiptsMessageIdReadRoute =
  ApiV1ReceiptsMessageIdReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => ApiV1ReceiptsMessageIdRoute,
  } as any)
const ApiV1PostageMessageIdSettleRoute =
  ApiV1PostageMessageIdSettleRouteImport.update({
    id: '/settle',
    path: '/settle',
    getParentRoute: () => ApiV1PostageMessageIdRoute,
  } as any)
const ApiV1PostageMessageIdRefundRoute =
  ApiV1PostageMessageIdRefundRouteImport.update({
    id: '/refund',
    path: '/refund',
    getParentRoute: () => ApiV1PostageMessageIdRoute,
  } as any)
const ApiV1AttachmentsAttachmentIdMetaRoute =
  ApiV1AttachmentsAttachmentIdMetaRouteImport.update({
    id: '/meta',
    path: '/meta',
    getParentRoute: () => ApiV1AttachmentsAttachmentIdRoute,
  } as any)
const ApiV1AttachmentsAttachmentIdFinalizeRoute =
  ApiV1AttachmentsAttachmentIdFinalizeRouteImport.update({
    id: '/finalize',
    path: '/finalize',
    getParentRoute: () => ApiV1AttachmentsAttachmentIdRoute,
  } as any)
const ApiV1PoliciesOwnerSendersSenderRoute =
  ApiV1PoliciesOwnerSendersSenderRouteImport.update({
    id: '/senders/$sender',
    path: '/senders/$sender',
    getParentRoute: () => ApiV1PoliciesOwnerRoute,
  } as any)
const ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute =
  ApiV1AttachmentsAttachmentIdChunksChunkIndexRouteImport.update({
    id: '/chunks/$chunkIndex',
    path: '/chunks/$chunkIndex',
    getParentRoute: () => ApiV1AttachmentsAttachmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/demo': typeof DemoRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/attachments/$attachmentId': typeof ApiV1AttachmentsAttachmentIdRouteWithChildren
  '/api/v1/attachments/initiate': typeof ApiV1AttachmentsInitiateRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/send/coordinate': typeof ApiV1SendCoordinateRoute
  '/api/v1/wallet/managed': typeof ApiV1WalletManagedRoute
  '/api/v1/wallet/status': typeof ApiV1WalletStatusRoute
  '/api/v1/accounts/': typeof ApiV1AccountsIndexRoute
  '/api/v1/contacts/': typeof ApiV1ContactsIndexRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts/': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/attachments/$attachmentId/finalize': typeof ApiV1AttachmentsAttachmentIdFinalizeRoute
  '/api/v1/attachments/$attachmentId/meta': typeof ApiV1AttachmentsAttachmentIdMetaRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/attachments/$attachmentId/chunks/$chunkIndex': typeof ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/demo': typeof DemoRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/attachments/$attachmentId': typeof ApiV1AttachmentsAttachmentIdRouteWithChildren
  '/api/v1/attachments/initiate': typeof ApiV1AttachmentsInitiateRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/send/coordinate': typeof ApiV1SendCoordinateRoute
  '/api/v1/wallet/managed': typeof ApiV1WalletManagedRoute
  '/api/v1/wallet/status': typeof ApiV1WalletStatusRoute
  '/api/v1/accounts': typeof ApiV1AccountsIndexRoute
  '/api/v1/contacts': typeof ApiV1ContactsIndexRoute
  '/api/v1/postage': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/attachments/$attachmentId/finalize': typeof ApiV1AttachmentsAttachmentIdFinalizeRoute
  '/api/v1/attachments/$attachmentId/meta': typeof ApiV1AttachmentsAttachmentIdMetaRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/attachments/$attachmentId/chunks/$chunkIndex': typeof ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/demo': typeof DemoRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/attachments/$attachmentId': typeof ApiV1AttachmentsAttachmentIdRouteWithChildren
  '/api/v1/attachments/initiate': typeof ApiV1AttachmentsInitiateRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/send/coordinate': typeof ApiV1SendCoordinateRoute
  '/api/v1/wallet/managed': typeof ApiV1WalletManagedRoute
  '/api/v1/wallet/status': typeof ApiV1WalletStatusRoute
  '/api/v1/accounts/': typeof ApiV1AccountsIndexRoute
  '/api/v1/contacts/': typeof ApiV1ContactsIndexRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts/': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/attachments/$attachmentId/finalize': typeof ApiV1AttachmentsAttachmentIdFinalizeRoute
  '/api/v1/attachments/$attachmentId/meta': typeof ApiV1AttachmentsAttachmentIdMetaRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/attachments/$attachmentId/chunks/$chunkIndex': typeof ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policy-editor'
    | '/demo'
    | '/motion-gallery'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/api/v1/bootstrap'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/attachments/$attachmentId'
    | '/api/v1/attachments/initiate'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/send/coordinate'
    | '/api/v1/wallet/managed'
    | '/api/v1/wallet/status'
    | '/api/v1/accounts/'
    | '/api/v1/contacts/'
    | '/api/v1/postage/'
    | '/api/v1/receipts/'
    | '/api/v1/attachments/$attachmentId/finalize'
    | '/api/v1/attachments/$attachmentId/meta'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/attachments/$attachmentId/chunks/$chunkIndex'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policy-editor'
    | '/demo'
    | '/motion-gallery'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/api/v1/bootstrap'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/attachments/$attachmentId'
    | '/api/v1/attachments/initiate'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/send/coordinate'
    | '/api/v1/wallet/managed'
    | '/api/v1/wallet/status'
    | '/api/v1/accounts'
    | '/api/v1/contacts'
    | '/api/v1/postage'
    | '/api/v1/receipts'
    | '/api/v1/attachments/$attachmentId/finalize'
    | '/api/v1/attachments/$attachmentId/meta'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/attachments/$attachmentId/chunks/$chunkIndex'
    | '/api/v1/policies/$owner/senders/$sender'
  id:
    | '__root__'
    | '/'
    | '/policy-editor'
    | '/demo'
    | '/motion-gallery'
    | '/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/api/v1/bootstrap'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/attachments/$attachmentId'
    | '/api/v1/attachments/initiate'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/send/coordinate'
    | '/api/v1/wallet/managed'
    | '/api/v1/wallet/status'
    | '/api/v1/accounts/'
    | '/api/v1/contacts/'
    | '/api/v1/postage/'
    | '/api/v1/receipts/'
    | '/api/v1/attachments/$attachmentId/finalize'
    | '/api/v1/attachments/$attachmentId/meta'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/attachments/$attachmentId/chunks/$chunkIndex'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolicyEditorRouteRoute: typeof PolicyEditorRouteRoute
  DemoRoute: typeof DemoRoute
  MotionGalleryRoute: typeof MotionGalleryRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ApiV1BootstrapRoute: typeof ApiV1BootstrapRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1ProtocolRoute: typeof ApiV1ProtocolRoute
  ApiV1AttachmentsAttachmentIdRoute: typeof ApiV1AttachmentsAttachmentIdRouteWithChildren
  ApiV1AttachmentsInitiateRoute: typeof ApiV1AttachmentsInitiateRoute
  ApiV1PoliciesOwnerRoute: typeof ApiV1PoliciesOwnerRouteWithChildren
  ApiV1PoliciesEvaluateRoute: typeof ApiV1PoliciesEvaluateRoute
  ApiV1PostageMessageIdRoute: typeof ApiV1PostageMessageIdRouteWithChildren
  ApiV1PostageQuoteRoute: typeof ApiV1PostageQuoteRoute
  ApiV1ReceiptsMessageIdRoute: typeof ApiV1ReceiptsMessageIdRouteWithChildren
  ApiV1RelayHealthRoute: typeof ApiV1RelayHealthRoute
  ApiV1RelayMessagesRoute: typeof ApiV1RelayMessagesRoute
  ApiV1RelayReadinessRoute: typeof ApiV1RelayReadinessRoute
  ApiV1RelayVersionRoute: typeof ApiV1RelayVersionRoute
  ApiV1SendCoordinateRoute: typeof ApiV1SendCoordinateRoute
  ApiV1WalletManagedRoute: typeof ApiV1WalletManagedRoute
  ApiV1WalletStatusRoute: typeof ApiV1WalletStatusRoute
  ApiV1AccountsIndexRoute: typeof ApiV1AccountsIndexRoute
  ApiV1ContactsIndexRoute: typeof ApiV1ContactsIndexRoute
  ApiV1PostageIndexRoute: typeof ApiV1PostageIndexRoute
  ApiV1ReceiptsIndexRoute: typeof ApiV1ReceiptsIndexRoute
  ApiV1RequestsIndexRoute: typeof ApiV1RequestsIndexRoute
  ApiV1AdminDlqIdRoute: typeof ApiV1AdminDlqIdRouteWithChildren
  ApiV1AdminJobsIdRoute: typeof ApiV1AdminJobsIdRoute
  ApiV1AuthPasswordResetCompleteRoute: typeof ApiV1AuthPasswordResetCompleteRoute
  ApiV1AuthPasswordResetRequestRoute: typeof ApiV1AuthPasswordResetRequestRoute
  ApiV1AuthRecoveryRedeemRoute: typeof ApiV1AuthRecoveryRedeemRoute
  ApiV1AuthRecoveryRegenerateRoute: typeof ApiV1AuthRecoveryRegenerateRoute
  ApiV1AuthRecoveryStatusRoute: typeof ApiV1AuthRecoveryStatusRoute
  ApiV1ContactsImportCommitRoute: typeof ApiV1ContactsImportCommitRoute
  ApiV1ContactsImportPreviewRoute: typeof ApiV1ContactsImportPreviewRoute
  ApiV1IdentityKeysKeyIdRoute: typeof ApiV1IdentityKeysKeyIdRoute
  ApiV1IdentityKeysRetireRoute: typeof ApiV1IdentityKeysRetireRoute
  ApiV1IdentityKeysRevokeRoute: typeof ApiV1IdentityKeysRevokeRoute
  ApiV1IdentityKeysRotateRoute: typeof ApiV1IdentityKeysRotateRoute
  ApiV1RequestsRequestIdDecisionsRoute: typeof ApiV1RequestsRequestIdDecisionsRoute
  ApiV1WalletLinkAddressRoute: typeof ApiV1WalletLinkAddressRoute
  ApiV1WalletLinkChallengeRoute: typeof ApiV1WalletLinkChallengeRoute
  ApiV1WalletLinkVerifyRoute: typeof ApiV1WalletLinkVerifyRoute
  ApiV1AdminDlqIndexRoute: typeof ApiV1AdminDlqIndexRoute
  ApiV1AdminFundingIndexRoute: typeof ApiV1AdminFundingIndexRoute
  ApiV1AdminJobsIndexRoute: typeof ApiV1AdminJobsIndexRoute
  ApiV1IdentityKeysIndexRoute: typeof ApiV1IdentityKeysIndexRoute
  ApiV1WalletLinkIndexRoute: typeof ApiV1WalletLinkIndexRoute
  ApiV1AccountsUserIdWalletProvisionRoute: typeof ApiV1AccountsUserIdWalletProvisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-gallery': {
      id: '/motion-gallery'
      path: '/motion-gallery'
      fullPath: '/motion-gallery'
      preLoaderRoute: typeof MotionGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-editor': {
      id: '/policy-editor'
      path: '/policy-editor'
      fullPath: '/policy-editor'
      preLoaderRoute: typeof PolicyEditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/protocol': {
      id: '/api/v1/protocol'
      path: '/api/v1/protocol'
      fullPath: '/api/v1/protocol'
      preLoaderRoute: typeof ApiV1ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bootstrap': {
      id: '/api/v1/bootstrap'
      path: '/api/v1/bootstrap'
      fullPath: '/api/v1/bootstrap'
      preLoaderRoute: typeof ApiV1BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/': {
      id: '/api/v1/requests/'
      path: '/api/v1/requests'
      fullPath: '/api/v1/requests/'
      preLoaderRoute: typeof ApiV1RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/': {
      id: '/api/v1/receipts/'
      path: '/api/v1/receipts'
      fullPath: '/api/v1/receipts/'
      preLoaderRoute: typeof ApiV1ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/': {
      id: '/api/v1/postage/'
      path: '/api/v1/postage'
      fullPath: '/api/v1/postage/'
      preLoaderRoute: typeof ApiV1PostageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts/': {
      id: '/api/v1/contacts/'
      path: '/api/v1/contacts'
      fullPath: '/api/v1/contacts/'
      preLoaderRoute: typeof ApiV1ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/': {
      id: '/api/v1/accounts/'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts/'
      preLoaderRoute: typeof ApiV1AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/status': {
      id: '/api/v1/wallet/status'
      path: '/api/v1/wallet/status'
      fullPath: '/api/v1/wallet/status'
      preLoaderRoute: typeof ApiV1WalletStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/managed': {
      id: '/api/v1/wallet/managed'
      path: '/api/v1/wallet/managed'
      fullPath: '/api/v1/wallet/managed'
      preLoaderRoute: typeof ApiV1WalletManagedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/send/coordinate': {
      id: '/api/v1/send/coordinate'
      path: '/api/v1/send/coordinate'
      fullPath: '/api/v1/send/coordinate'
      preLoaderRoute: typeof ApiV1SendCoordinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/version': {
      id: '/api/v1/relay/version'
      path: '/api/v1/relay/version'
      fullPath: '/api/v1/relay/version'
      preLoaderRoute: typeof ApiV1RelayVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/readiness': {
      id: '/api/v1/relay/readiness'
      path: '/api/v1/relay/readiness'
      fullPath: '/api/v1/relay/readiness'
      preLoaderRoute: typeof ApiV1RelayReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/messages': {
      id: '/api/v1/relay/messages'
      path: '/api/v1/relay/messages'
      fullPath: '/api/v1/relay/messages'
      preLoaderRoute: typeof ApiV1RelayMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/health': {
      id: '/api/v1/relay/health'
      path: '/api/v1/relay/health'
      fullPath: '/api/v1/relay/health'
      preLoaderRoute: typeof ApiV1RelayHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/$messageId': {
      id: '/api/v1/receipts/$messageId'
      path: '/api/v1/receipts/$messageId'
      fullPath: '/api/v1/receipts/$messageId'
      preLoaderRoute: typeof ApiV1ReceiptsMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/quote': {
      id: '/api/v1/postage/quote'
      path: '/api/v1/postage/quote'
      fullPath: '/api/v1/postage/quote'
      preLoaderRoute: typeof ApiV1PostageQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/$messageId': {
      id: '/api/v1/postage/$messageId'
      path: '/api/v1/postage/$messageId'
      fullPath: '/api/v1/postage/$messageId'
      preLoaderRoute: typeof ApiV1PostageMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/evaluate': {
      id: '/api/v1/policies/evaluate'
      path: '/api/v1/policies/evaluate'
      fullPath: '/api/v1/policies/evaluate'
      preLoaderRoute: typeof ApiV1PoliciesEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/$owner': {
      id: '/api/v1/policies/$owner'
      path: '/api/v1/policies/$owner'
      fullPath: '/api/v1/policies/$owner'
      preLoaderRoute: typeof ApiV1PoliciesOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attachments/initiate': {
      id: '/api/v1/attachments/initiate'
      path: '/api/v1/attachments/initiate'
      fullPath: '/api/v1/attachments/initiate'
      preLoaderRoute: typeof ApiV1AttachmentsInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attachments/$attachmentId': {
      id: '/api/v1/attachments/$attachmentId'
      path: '/api/v1/attachments/$attachmentId'
      fullPath: '/api/v1/attachments/$attachmentId'
      preLoaderRoute: typeof ApiV1AttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/requests/$requestId/decisions': {
      id: '/api/v1/requests/$requestId/decisions'
      path: '/api/v1/requests/$requestId/decisions'
      fullPath: '/api/v1/requests/$requestId/decisions'
      preLoaderRoute: typeof ApiV1RequestsRequestIdDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/$messageId/read': {
      id: '/api/v1/receipts/$messageId/read'
      path: '/read'
      fullPath: '/api/v1/receipts/$messageId/read'
      preLoaderRoute: typeof ApiV1ReceiptsMessageIdReadRouteImport
      parentRoute: typeof ApiV1ReceiptsMessageIdRoute
    }
    '/api/v1/postage/$messageId/settle': {
      id: '/api/v1/postage/$messageId/settle'
      path: '/settle'
      fullPath: '/api/v1/postage/$messageId/settle'
      preLoaderRoute: typeof ApiV1PostageMessageIdSettleRouteImport
      parentRoute: typeof ApiV1PostageMessageIdRoute
    }
    '/api/v1/postage/$messageId/refund': {
      id: '/api/v1/postage/$messageId/refund'
      path: '/refund'
      fullPath: '/api/v1/postage/$messageId/refund'
      preLoaderRoute: typeof ApiV1PostageMessageIdRefundRouteImport
      parentRoute: typeof ApiV1PostageMessageIdRoute
    }
    '/api/v1/attachments/$attachmentId/meta': {
      id: '/api/v1/attachments/$attachmentId/meta'
      path: '/meta'
      fullPath: '/api/v1/attachments/$attachmentId/meta'
      preLoaderRoute: typeof ApiV1AttachmentsAttachmentIdMetaRouteImport
      parentRoute: typeof ApiV1AttachmentsAttachmentIdRoute
    }
    '/api/v1/attachments/$attachmentId/finalize': {
      id: '/api/v1/attachments/$attachmentId/finalize'
      path: '/finalize'
      fullPath: '/api/v1/attachments/$attachmentId/finalize'
      preLoaderRoute: typeof ApiV1AttachmentsAttachmentIdFinalizeRouteImport
      parentRoute: typeof ApiV1AttachmentsAttachmentIdRoute
    }
    '/api/v1/contacts/import/preview': {
      id: '/api/v1/contacts/import/preview'
      path: '/api/v1/contacts/import/preview'
      fullPath: '/api/v1/contacts/import/preview'
      preLoaderRoute: typeof ApiV1ContactsImportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts/import/commit': {
      id: '/api/v1/contacts/import/commit'
      path: '/api/v1/contacts/import/commit'
      fullPath: '/api/v1/contacts/import/commit'
      preLoaderRoute: typeof ApiV1ContactsImportCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/recovery/status': {
      id: '/api/v1/auth/recovery/status'
      path: '/api/v1/auth/recovery/status'
      fullPath: '/api/v1/auth/recovery/status'
      preLoaderRoute: typeof ApiV1AuthRecoveryStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/recovery/regenerate': {
      id: '/api/v1/auth/recovery/regenerate'
      path: '/api/v1/auth/recovery/regenerate'
      fullPath: '/api/v1/auth/recovery/regenerate'
      preLoaderRoute: typeof ApiV1AuthRecoveryRegenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/recovery/redeem': {
      id: '/api/v1/auth/recovery/redeem'
      path: '/api/v1/auth/recovery/redeem'
      fullPath: '/api/v1/auth/recovery/redeem'
      preLoaderRoute: typeof ApiV1AuthRecoveryRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/password-reset/request': {
      id: '/api/v1/auth/password-reset/request'
      path: '/api/v1/auth/password-reset/request'
      fullPath: '/api/v1/auth/password-reset/request'
      preLoaderRoute: typeof ApiV1AuthPasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/password-reset/complete': {
      id: '/api/v1/auth/password-reset/complete'
      path: '/api/v1/auth/password-reset/complete'
      fullPath: '/api/v1/auth/password-reset/complete'
      preLoaderRoute: typeof ApiV1AuthPasswordResetCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/jobs/$id': {
      id: '/api/v1/admin/jobs/$id'
      path: '/api/v1/admin/jobs/$id'
      fullPath: '/api/v1/admin/jobs/$id'
      preLoaderRoute: typeof ApiV1AdminJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/dlq/$id': {
      id: '/api/v1/admin/dlq/$id'
      path: '/api/v1/admin/dlq/$id'
      fullPath: '/api/v1/admin/dlq/$id'
      preLoaderRoute: typeof ApiV1AdminDlqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/provisioning/retry': {
      id: '/api/v1/accounts/provisioning/retry'
      path: '/retry'
      fullPath: '/api/v1/accounts/provisioning/retry'
      preLoaderRoute: typeof ApiV1AccountsProvisioningRetryRouteImport
      parentRoute: typeof ApiV1AccountsProvisioningRoute
    }
    '/api/v1/policies/$owner/senders/$sender': {
      id: '/api/v1/policies/$owner/senders/$sender'
      path: '/senders/$sender'
      fullPath: '/api/v1/policies/$owner/senders/$sender'
      preLoaderRoute: typeof ApiV1PoliciesOwnerSendersSenderRouteImport
      parentRoute: typeof ApiV1PoliciesOwnerRoute
    }
    '/api/v1/attachments/$attachmentId/chunks/$chunkIndex': {
      id: '/api/v1/attachments/$attachmentId/chunks/$chunkIndex'
      path: '/chunks/$chunkIndex'
      fullPath: '/api/v1/attachments/$attachmentId/chunks/$chunkIndex'
      preLoaderRoute: typeof ApiV1AttachmentsAttachmentIdChunksChunkIndexRouteImport
      parentRoute: typeof ApiV1AttachmentsAttachmentIdRoute
    }
  }
}

interface ApiV1AttachmentsAttachmentIdRouteChildren {
  ApiV1AttachmentsAttachmentIdFinalizeRoute: typeof ApiV1AttachmentsAttachmentIdFinalizeRoute
  ApiV1AttachmentsAttachmentIdMetaRoute: typeof ApiV1AttachmentsAttachmentIdMetaRoute
  ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute: typeof ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute
}

const ApiV1AttachmentsAttachmentIdRouteChildren: ApiV1AttachmentsAttachmentIdRouteChildren =
  {
    ApiV1AttachmentsAttachmentIdFinalizeRoute:
      ApiV1AttachmentsAttachmentIdFinalizeRoute,
    ApiV1AttachmentsAttachmentIdMetaRoute:
      ApiV1AttachmentsAttachmentIdMetaRoute,
    ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute:
      ApiV1AttachmentsAttachmentIdChunksChunkIndexRoute,
  }

const ApiV1AttachmentsAttachmentIdRouteWithChildren =
  ApiV1AttachmentsAttachmentIdRoute._addFileChildren(
    ApiV1AttachmentsAttachmentIdRouteChildren,
  )

interface ApiV1PoliciesOwnerRouteChildren {
  ApiV1PoliciesOwnerProvisionRoute: typeof ApiV1PoliciesOwnerProvisionRoute
  ApiV1PoliciesOwnerReconciliationRoute: typeof ApiV1PoliciesOwnerReconciliationRoute
  ApiV1PoliciesOwnerSendersSenderRoute: typeof ApiV1PoliciesOwnerSendersSenderRoute
}

const ApiV1PoliciesOwnerRouteChildren: ApiV1PoliciesOwnerRouteChildren = {
  ApiV1PoliciesOwnerProvisionRoute: ApiV1PoliciesOwnerProvisionRoute,
  ApiV1PoliciesOwnerReconciliationRoute: ApiV1PoliciesOwnerReconciliationRoute,
  ApiV1PoliciesOwnerSendersSenderRoute: ApiV1PoliciesOwnerSendersSenderRoute,
}

const ApiV1PoliciesOwnerRouteWithChildren =
  ApiV1PoliciesOwnerRoute._addFileChildren(ApiV1PoliciesOwnerRouteChildren)

interface ApiV1PostageMessageIdRouteChildren {
  ApiV1PostageMessageIdRefundRoute: typeof ApiV1PostageMessageIdRefundRoute
  ApiV1PostageMessageIdSettleRoute: typeof ApiV1PostageMessageIdSettleRoute
}

const ApiV1PostageMessageIdRouteChildren: ApiV1PostageMessageIdRouteChildren = {
  ApiV1PostageMessageIdRefundRoute: ApiV1PostageMessageIdRefundRoute,
  ApiV1PostageMessageIdSettleRoute: ApiV1PostageMessageIdSettleRoute,
}

const ApiV1PostageMessageIdRouteWithChildren =
  ApiV1PostageMessageIdRoute._addFileChildren(
    ApiV1PostageMessageIdRouteChildren,
  )

interface ApiV1ReceiptsMessageIdRouteChildren {
  ApiV1ReceiptsMessageIdReadRoute: typeof ApiV1ReceiptsMessageIdReadRoute
}

const ApiV1ReceiptsMessageIdRouteChildren: ApiV1ReceiptsMessageIdRouteChildren =
  {
    ApiV1ReceiptsMessageIdReadRoute: ApiV1ReceiptsMessageIdReadRoute,
  }

const ApiV1ReceiptsMessageIdRouteWithChildren =
  ApiV1ReceiptsMessageIdRoute._addFileChildren(
    ApiV1ReceiptsMessageIdRouteChildren,
  )

interface ApiV1AdminDlqIdRouteChildren {
  ApiV1AdminDlqIdAbandonRoute: typeof ApiV1AdminDlqIdAbandonRoute
  ApiV1AdminDlqIdRetryRoute: typeof ApiV1AdminDlqIdRetryRoute
}

const ApiV1AdminDlqIdRouteChildren: ApiV1AdminDlqIdRouteChildren = {
  ApiV1AdminDlqIdAbandonRoute: ApiV1AdminDlqIdAbandonRoute,
  ApiV1AdminDlqIdRetryRoute: ApiV1AdminDlqIdRetryRoute,
}

const ApiV1AdminDlqIdRouteWithChildren = ApiV1AdminDlqIdRoute._addFileChildren(
  ApiV1AdminDlqIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolicyEditorRouteRoute: PolicyEditorRouteRoute,
  DemoRoute: DemoRoute,
  MotionGalleryRoute: MotionGalleryRoute,
  OnboardingRoute: OnboardingRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ApiV1BootstrapRoute: ApiV1BootstrapRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1ProtocolRoute: ApiV1ProtocolRoute,
  ApiV1AttachmentsAttachmentIdRoute:
    ApiV1AttachmentsAttachmentIdRouteWithChildren,
  ApiV1AttachmentsInitiateRoute: ApiV1AttachmentsInitiateRoute,
  ApiV1PoliciesOwnerRoute: ApiV1PoliciesOwnerRouteWithChildren,
  ApiV1PoliciesEvaluateRoute: ApiV1PoliciesEvaluateRoute,
  ApiV1PostageMessageIdRoute: ApiV1PostageMessageIdRouteWithChildren,
  ApiV1PostageQuoteRoute: ApiV1PostageQuoteRoute,
  ApiV1ReceiptsMessageIdRoute: ApiV1ReceiptsMessageIdRouteWithChildren,
  ApiV1RelayHealthRoute: ApiV1RelayHealthRoute,
  ApiV1RelayMessagesRoute: ApiV1RelayMessagesRoute,
  ApiV1RelayReadinessRoute: ApiV1RelayReadinessRoute,
  ApiV1RelayVersionRoute: ApiV1RelayVersionRoute,
  ApiV1SendCoordinateRoute: ApiV1SendCoordinateRoute,
  ApiV1WalletManagedRoute: ApiV1WalletManagedRoute,
  ApiV1WalletStatusRoute: ApiV1WalletStatusRoute,
  ApiV1AccountsIndexRoute: ApiV1AccountsIndexRoute,
  ApiV1ContactsIndexRoute: ApiV1ContactsIndexRoute,
  ApiV1PostageIndexRoute: ApiV1PostageIndexRoute,
  ApiV1ReceiptsIndexRoute: ApiV1ReceiptsIndexRoute,
  ApiV1RequestsIndexRoute: ApiV1RequestsIndexRoute,
  ApiV1AdminDlqIdRoute: ApiV1AdminDlqIdRouteWithChildren,
  ApiV1AdminJobsIdRoute: ApiV1AdminJobsIdRoute,
  ApiV1AuthPasswordResetCompleteRoute: ApiV1AuthPasswordResetCompleteRoute,
  ApiV1AuthPasswordResetRequestRoute: ApiV1AuthPasswordResetRequestRoute,
  ApiV1AuthRecoveryRedeemRoute: ApiV1AuthRecoveryRedeemRoute,
  ApiV1AuthRecoveryRegenerateRoute: ApiV1AuthRecoveryRegenerateRoute,
  ApiV1AuthRecoveryStatusRoute: ApiV1AuthRecoveryStatusRoute,
  ApiV1ContactsImportCommitRoute: ApiV1ContactsImportCommitRoute,
  ApiV1ContactsImportPreviewRoute: ApiV1ContactsImportPreviewRoute,
  ApiV1IdentityKeysKeyIdRoute: ApiV1IdentityKeysKeyIdRoute,
  ApiV1IdentityKeysRetireRoute: ApiV1IdentityKeysRetireRoute,
  ApiV1IdentityKeysRevokeRoute: ApiV1IdentityKeysRevokeRoute,
  ApiV1IdentityKeysRotateRoute: ApiV1IdentityKeysRotateRoute,
  ApiV1RequestsRequestIdDecisionsRoute: ApiV1RequestsRequestIdDecisionsRoute,
  ApiV1WalletLinkAddressRoute: ApiV1WalletLinkAddressRoute,
  ApiV1WalletLinkChallengeRoute: ApiV1WalletLinkChallengeRoute,
  ApiV1WalletLinkVerifyRoute: ApiV1WalletLinkVerifyRoute,
  ApiV1AdminDlqIndexRoute: ApiV1AdminDlqIndexRoute,
  ApiV1AdminFundingIndexRoute: ApiV1AdminFundingIndexRoute,
  ApiV1AdminJobsIndexRoute: ApiV1AdminJobsIndexRoute,
  ApiV1IdentityKeysIndexRoute: ApiV1IdentityKeysIndexRoute,
  ApiV1WalletLinkIndexRoute: ApiV1WalletLinkIndexRoute,
  ApiV1AccountsUserIdWalletProvisionRoute:
    ApiV1AccountsUserIdWalletProvisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
