/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotionGalleryRouteImport } from './routes/motion-gallery'
import { Route as PolicyEditorRouteRouteImport } from './routes/policy-editor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1ProtocolRouteImport } from './routes/api/v1/protocol'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1ReceiptsIndexRouteImport } from './routes/api/v1/receipts/index'
import { Route as ApiV1PostageIndexRouteImport } from './routes/api/v1/postage/index'
import { Route as ApiV1RelayVersionRouteImport } from './routes/api/v1/relay/version'
import { Route as ApiV1RelayReadinessRouteImport } from './routes/api/v1/relay/readiness'
import { Route as ApiV1RelayMessagesRouteImport } from './routes/api/v1/relay/messages'
import { Route as ApiV1RelayHealthRouteImport } from './routes/api/v1/relay/health'
import { Route as ApiV1MailboxSyncRouteImport } from './routes/api/v1/mailbox/sync'
import { Route as ApiV1ReceiptsMessageIdRouteImport } from './routes/api/v1/receipts/$messageId'
import { Route as ApiV1PostageQuoteRouteImport } from './routes/api/v1/postage/quote'
import { Route as ApiV1PostageMessageIdRouteImport } from './routes/api/v1/postage/$messageId'
import { Route as ApiV1PoliciesEvaluateRouteImport } from './routes/api/v1/policies/evaluate'
import { Route as ApiV1PoliciesOwnerRouteImport } from './routes/api/v1/policies/$owner'
import { Route as ApiV1AuthSessionRouteImport } from './routes/api/v1/auth/session'
import { Route as ApiV1AuthRegisterRouteImport } from './routes/api/v1/auth/register'
import { Route as ApiV1AuthLogoutAllRouteImport } from './routes/api/v1/auth/logout-all'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1WalletLinkIndexRouteImport } from './routes/api/v1/wallet/link/index'
import { Route as ApiV1WalletLinkVerifyRouteImport } from './routes/api/v1/wallet/link/verify'
import { Route as ApiV1WalletLinkChallengeRouteImport } from './routes/api/v1/wallet/link/challenge'
import { Route as ApiV1WalletLinkAddressRouteImport } from './routes/api/v1/wallet/link/$address'
import { Route as ApiV1ReceiptsMessageIdReadRouteImport } from './routes/api/v1/receipts/$messageId/read'
import { Route as ApiV1PostageMessageIdSettleRouteImport } from './routes/api/v1/postage/$messageId/settle'
import { Route as ApiV1PostageMessageIdRefundRouteImport } from './routes/api/v1/postage/$messageId/refund'
import { Route as ApiV1PoliciesOwnerReconciliationRouteImport } from './routes/api/v1/policies/$owner/reconciliation'
import { Route as ApiV1PoliciesOwnerProvisionRouteImport } from './routes/api/v1/policies/$owner/provision'
import { Route as ApiV1PoliciesOwnerSendersSenderRouteImport } from './routes/api/v1/policies/$owner/senders/$sender'

const MotionGalleryRoute = MotionGalleryRouteImport.update({
  id: '/motion-gallery',
  path: '/motion-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyEditorRouteRoute = PolicyEditorRouteRouteImport.update({
  id: '/policy-editor',
  path: '/policy-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProtocolRoute = ApiV1ProtocolRouteImport.update({
  id: '/api/v1/protocol',
  path: '/api/v1/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReceiptsIndexRoute = ApiV1ReceiptsIndexRouteImport.update({
  id: '/api/v1/receipts/',
  path: '/api/v1/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageIndexRoute = ApiV1PostageIndexRouteImport.update({
  id: '/api/v1/postage/',
  path: '/api/v1/postage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayVersionRoute = ApiV1RelayVersionRouteImport.update({
  id: '/api/v1/relay/version',
  path: '/api/v1/relay/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayReadinessRoute = ApiV1RelayReadinessRouteImport.update({
  id: '/api/v1/relay/readiness',
  path: '/api/v1/relay/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayMessagesRoute = ApiV1RelayMessagesRouteImport.update({
  id: '/api/v1/relay/messages',
  path: '/api/v1/relay/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RelayHealthRoute = ApiV1RelayHealthRouteImport.update({
  id: '/api/v1/relay/health',
  path: '/api/v1/relay/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MailboxSyncRoute = ApiV1MailboxSyncRouteImport.update({
  id: '/api/v1/mailbox/sync',
  path: '/api/v1/mailbox/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReceiptsMessageIdRoute = ApiV1ReceiptsMessageIdRouteImport.update({
  id: '/api/v1/receipts/$messageId',
  path: '/api/v1/receipts/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageQuoteRoute = ApiV1PostageQuoteRouteImport.update({
  id: '/api/v1/postage/quote',
  path: '/api/v1/postage/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostageMessageIdRoute = ApiV1PostageMessageIdRouteImport.update({
  id: '/api/v1/postage/$messageId',
  path: '/api/v1/postage/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesEvaluateRoute = ApiV1PoliciesEvaluateRouteImport.update({
  id: '/api/v1/policies/evaluate',
  path: '/api/v1/policies/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PoliciesOwnerRoute = ApiV1PoliciesOwnerRouteImport.update({
  id: '/api/v1/policies/$owner',
  path: '/api/v1/policies/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSessionRoute = ApiV1AuthSessionRouteImport.update({
  id: '/api/v1/auth/session',
  path: '/api/v1/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthRegisterRoute = ApiV1AuthRegisterRouteImport.update({
  id: '/api/v1/auth/register',
  path: '/api/v1/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutAllRoute = ApiV1AuthLogoutAllRouteImport.update({
  id: '/api/v1/auth/logout-all',
  path: '/api/v1/auth/logout-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletLinkIndexRoute = ApiV1WalletLinkIndexRouteImport.update({
  id: '/api/v1/wallet/link/',
  path: '/api/v1/wallet/link/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletLinkVerifyRoute = ApiV1WalletLinkVerifyRouteImport.update({
  id: '/api/v1/wallet/link/verify',
  path: '/api/v1/wallet/link/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletLinkChallengeRoute =
  ApiV1WalletLinkChallengeRouteImport.update({
    id: '/api/v1/wallet/link/challenge',
    path: '/api/v1/wallet/link/challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WalletLinkAddressRoute = ApiV1WalletLinkAddressRouteImport.update({
  id: '/api/v1/wallet/link/$address',
  path: '/api/v1/wallet/link/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReceiptsMessageIdReadRoute =
  ApiV1ReceiptsMessageIdReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => ApiV1ReceiptsMessageIdRoute,
  } as any)
const ApiV1PostageMessageIdSettleRoute =
  ApiV1PostageMessageIdSettleRouteImport.update({
    id: '/settle',
    path: '/settle',
    getParentRoute: () => ApiV1PostageMessageIdRoute,
  } as any)
const ApiV1PostageMessageIdRefundRoute =
  ApiV1PostageMessageIdRefundRouteImport.update({
    id: '/refund',
    path: '/refund',
    getParentRoute: () => ApiV1PostageMessageIdRoute,
  } as any)
const ApiV1PoliciesOwnerReconciliationRoute =
  ApiV1PoliciesOwnerReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => ApiV1PoliciesOwnerRoute,
  } as any)
const ApiV1PoliciesOwnerProvisionRoute =
  ApiV1PoliciesOwnerProvisionRouteImport.update({
    id: '/provision',
    path: '/provision',
    getParentRoute: () => ApiV1PoliciesOwnerRoute,
  } as any)
const ApiV1PoliciesOwnerSendersSenderRoute =
  ApiV1PoliciesOwnerSendersSenderRouteImport.update({
    id: '/senders/$sender',
    path: '/senders/$sender',
    getParentRoute: () => ApiV1PoliciesOwnerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/logout-all': typeof ApiV1AuthLogoutAllRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/mailbox/sync': typeof ApiV1MailboxSyncRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts/': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/policies/$owner/provision': typeof ApiV1PoliciesOwnerProvisionRoute
  '/api/v1/policies/$owner/reconciliation': typeof ApiV1PoliciesOwnerReconciliationRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/wallet/link/$address': typeof ApiV1WalletLinkAddressRoute
  '/api/v1/wallet/link/challenge': typeof ApiV1WalletLinkChallengeRoute
  '/api/v1/wallet/link/verify': typeof ApiV1WalletLinkVerifyRoute
  '/api/v1/wallet/link/': typeof ApiV1WalletLinkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/logout-all': typeof ApiV1AuthLogoutAllRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/mailbox/sync': typeof ApiV1MailboxSyncRoute
  '/api/v1/postage': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/policies/$owner/provision': typeof ApiV1PoliciesOwnerProvisionRoute
  '/api/v1/policies/$owner/reconciliation': typeof ApiV1PoliciesOwnerReconciliationRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/wallet/link/$address': typeof ApiV1WalletLinkAddressRoute
  '/api/v1/wallet/link/challenge': typeof ApiV1WalletLinkChallengeRoute
  '/api/v1/wallet/link/verify': typeof ApiV1WalletLinkVerifyRoute
  '/api/v1/wallet/link': typeof ApiV1WalletLinkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policy-editor': typeof PolicyEditorRouteRoute
  '/motion-gallery': typeof MotionGalleryRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/protocol': typeof ApiV1ProtocolRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/logout-all': typeof ApiV1AuthLogoutAllRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/policies/$owner': typeof ApiV1PoliciesOwnerRouteWithChildren
  '/api/v1/policies/evaluate': typeof ApiV1PoliciesEvaluateRoute
  '/api/v1/postage/$messageId': typeof ApiV1PostageMessageIdRouteWithChildren
  '/api/v1/postage/quote': typeof ApiV1PostageQuoteRoute
  '/api/v1/receipts/$messageId': typeof ApiV1ReceiptsMessageIdRouteWithChildren
  '/api/v1/relay/health': typeof ApiV1RelayHealthRoute
  '/api/v1/relay/messages': typeof ApiV1RelayMessagesRoute
  '/api/v1/relay/readiness': typeof ApiV1RelayReadinessRoute
  '/api/v1/relay/version': typeof ApiV1RelayVersionRoute
  '/api/v1/mailbox/sync': typeof ApiV1MailboxSyncRoute
  '/api/v1/postage/': typeof ApiV1PostageIndexRoute
  '/api/v1/receipts/': typeof ApiV1ReceiptsIndexRoute
  '/api/v1/policies/$owner/provision': typeof ApiV1PoliciesOwnerProvisionRoute
  '/api/v1/policies/$owner/reconciliation': typeof ApiV1PoliciesOwnerReconciliationRoute
  '/api/v1/postage/$messageId/refund': typeof ApiV1PostageMessageIdRefundRoute
  '/api/v1/postage/$messageId/settle': typeof ApiV1PostageMessageIdSettleRoute
  '/api/v1/receipts/$messageId/read': typeof ApiV1ReceiptsMessageIdReadRoute
  '/api/v1/wallet/link/$address': typeof ApiV1WalletLinkAddressRoute
  '/api/v1/wallet/link/challenge': typeof ApiV1WalletLinkChallengeRoute
  '/api/v1/wallet/link/verify': typeof ApiV1WalletLinkVerifyRoute
  '/api/v1/wallet/link/': typeof ApiV1WalletLinkIndexRoute
  '/api/v1/policies/$owner/senders/$sender': typeof ApiV1PoliciesOwnerSendersSenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/policy-editor'
    | '/motion-gallery'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/logout-all'
    | '/api/v1/auth/register'
    | '/api/v1/auth/session'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/mailbox/sync'
    | '/api/v1/postage/'
    | '/api/v1/receipts/'
    | '/api/v1/policies/$owner/provision'
    | '/api/v1/policies/$owner/reconciliation'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/wallet/link/$address'
    | '/api/v1/wallet/link/challenge'
    | '/api/v1/wallet/link/verify'
    | '/api/v1/wallet/link/'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/policy-editor'
    | '/motion-gallery'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/logout-all'
    | '/api/v1/auth/register'
    | '/api/v1/auth/session'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/mailbox/sync'
    | '/api/v1/postage'
    | '/api/v1/receipts'
    | '/api/v1/policies/$owner/provision'
    | '/api/v1/policies/$owner/reconciliation'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/wallet/link/$address'
    | '/api/v1/wallet/link/challenge'
    | '/api/v1/wallet/link/verify'
    | '/api/v1/wallet/link'
    | '/api/v1/policies/$owner/senders/$sender'
  id:
    | '__root__'
    | '/'
    | '/policy-editor'
    | '/motion-gallery'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/protocol'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/logout-all'
    | '/api/v1/auth/register'
    | '/api/v1/auth/session'
    | '/api/v1/policies/$owner'
    | '/api/v1/policies/evaluate'
    | '/api/v1/postage/$messageId'
    | '/api/v1/postage/quote'
    | '/api/v1/receipts/$messageId'
    | '/api/v1/relay/health'
    | '/api/v1/relay/messages'
    | '/api/v1/relay/readiness'
    | '/api/v1/relay/version'
    | '/api/v1/mailbox/sync'
    | '/api/v1/postage/'
    | '/api/v1/receipts/'
    | '/api/v1/policies/$owner/provision'
    | '/api/v1/policies/$owner/reconciliation'
    | '/api/v1/postage/$messageId/refund'
    | '/api/v1/postage/$messageId/settle'
    | '/api/v1/receipts/$messageId/read'
    | '/api/v1/wallet/link/$address'
    | '/api/v1/wallet/link/challenge'
    | '/api/v1/wallet/link/verify'
    | '/api/v1/wallet/link/'
    | '/api/v1/policies/$owner/senders/$sender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolicyEditorRouteRoute: typeof PolicyEditorRouteRoute
  MotionGalleryRoute: typeof MotionGalleryRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1ProtocolRoute: typeof ApiV1ProtocolRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthLogoutAllRoute: typeof ApiV1AuthLogoutAllRoute
  ApiV1AuthRegisterRoute: typeof ApiV1AuthRegisterRoute
  ApiV1AuthSessionRoute: typeof ApiV1AuthSessionRoute
  ApiV1PoliciesOwnerRoute: typeof ApiV1PoliciesOwnerRouteWithChildren
  ApiV1PoliciesEvaluateRoute: typeof ApiV1PoliciesEvaluateRoute
  ApiV1PostageMessageIdRoute: typeof ApiV1PostageMessageIdRouteWithChildren
  ApiV1PostageQuoteRoute: typeof ApiV1PostageQuoteRoute
  ApiV1ReceiptsMessageIdRoute: typeof ApiV1ReceiptsMessageIdRouteWithChildren
  ApiV1RelayHealthRoute: typeof ApiV1RelayHealthRoute
  ApiV1RelayMessagesRoute: typeof ApiV1RelayMessagesRoute
  ApiV1RelayReadinessRoute: typeof ApiV1RelayReadinessRoute
  ApiV1RelayVersionRoute: typeof ApiV1RelayVersionRoute
  ApiV1MailboxSyncRoute: typeof ApiV1MailboxSyncRoute
  ApiV1PostageIndexRoute: typeof ApiV1PostageIndexRoute
  ApiV1ReceiptsIndexRoute: typeof ApiV1ReceiptsIndexRoute
  ApiV1WalletLinkAddressRoute: typeof ApiV1WalletLinkAddressRoute
  ApiV1WalletLinkChallengeRoute: typeof ApiV1WalletLinkChallengeRoute
  ApiV1WalletLinkVerifyRoute: typeof ApiV1WalletLinkVerifyRoute
  ApiV1WalletLinkIndexRoute: typeof ApiV1WalletLinkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motion-gallery': {
      id: '/motion-gallery'
      path: '/motion-gallery'
      fullPath: '/motion-gallery'
      preLoaderRoute: typeof MotionGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-editor': {
      id: '/policy-editor'
      path: '/policy-editor'
      fullPath: '/policy-editor'
      preLoaderRoute: typeof PolicyEditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/protocol': {
      id: '/api/v1/protocol'
      path: '/api/v1/protocol'
      fullPath: '/api/v1/protocol'
      preLoaderRoute: typeof ApiV1ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/': {
      id: '/api/v1/receipts/'
      path: '/api/v1/receipts'
      fullPath: '/api/v1/receipts/'
      preLoaderRoute: typeof ApiV1ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/': {
      id: '/api/v1/postage/'
      path: '/api/v1/postage'
      fullPath: '/api/v1/postage/'
      preLoaderRoute: typeof ApiV1PostageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/version': {
      id: '/api/v1/relay/version'
      path: '/api/v1/relay/version'
      fullPath: '/api/v1/relay/version'
      preLoaderRoute: typeof ApiV1RelayVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mailbox/sync': {
      id: '/api/v1/mailbox/sync'
      path: '/api/v1/mailbox/sync'
      fullPath: '/api/v1/mailbox/sync'
      preLoaderRoute: typeof ApiV1MailboxSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/readiness': {
      id: '/api/v1/relay/readiness'
      path: '/api/v1/relay/readiness'
      fullPath: '/api/v1/relay/readiness'
      preLoaderRoute: typeof ApiV1RelayReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/messages': {
      id: '/api/v1/relay/messages'
      path: '/api/v1/relay/messages'
      fullPath: '/api/v1/relay/messages'
      preLoaderRoute: typeof ApiV1RelayMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/relay/health': {
      id: '/api/v1/relay/health'
      path: '/api/v1/relay/health'
      fullPath: '/api/v1/relay/health'
      preLoaderRoute: typeof ApiV1RelayHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/$messageId': {
      id: '/api/v1/receipts/$messageId'
      path: '/api/v1/receipts/$messageId'
      fullPath: '/api/v1/receipts/$messageId'
      preLoaderRoute: typeof ApiV1ReceiptsMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/quote': {
      id: '/api/v1/postage/quote'
      path: '/api/v1/postage/quote'
      fullPath: '/api/v1/postage/quote'
      preLoaderRoute: typeof ApiV1PostageQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/postage/$messageId': {
      id: '/api/v1/postage/$messageId'
      path: '/api/v1/postage/$messageId'
      fullPath: '/api/v1/postage/$messageId'
      preLoaderRoute: typeof ApiV1PostageMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/evaluate': {
      id: '/api/v1/policies/evaluate'
      path: '/api/v1/policies/evaluate'
      fullPath: '/api/v1/policies/evaluate'
      preLoaderRoute: typeof ApiV1PoliciesEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/policies/$owner': {
      id: '/api/v1/policies/$owner'
      path: '/api/v1/policies/$owner'
      fullPath: '/api/v1/policies/$owner'
      preLoaderRoute: typeof ApiV1PoliciesOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/session': {
      id: '/api/v1/auth/session'
      path: '/api/v1/auth/session'
      fullPath: '/api/v1/auth/session'
      preLoaderRoute: typeof ApiV1AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/register': {
      id: '/api/v1/auth/register'
      path: '/api/v1/auth/register'
      fullPath: '/api/v1/auth/register'
      preLoaderRoute: typeof ApiV1AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout-all': {
      id: '/api/v1/auth/logout-all'
      path: '/api/v1/auth/logout-all'
      fullPath: '/api/v1/auth/logout-all'
      preLoaderRoute: typeof ApiV1AuthLogoutAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/link/': {
      id: '/api/v1/wallet/link/'
      path: '/api/v1/wallet/link'
      fullPath: '/api/v1/wallet/link/'
      preLoaderRoute: typeof ApiV1WalletLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/link/verify': {
      id: '/api/v1/wallet/link/verify'
      path: '/api/v1/wallet/link/verify'
      fullPath: '/api/v1/wallet/link/verify'
      preLoaderRoute: typeof ApiV1WalletLinkVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/link/challenge': {
      id: '/api/v1/wallet/link/challenge'
      path: '/api/v1/wallet/link/challenge'
      fullPath: '/api/v1/wallet/link/challenge'
      preLoaderRoute: typeof ApiV1WalletLinkChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet/link/$address': {
      id: '/api/v1/wallet/link/$address'
      path: '/api/v1/wallet/link/$address'
      fullPath: '/api/v1/wallet/link/$address'
      preLoaderRoute: typeof ApiV1WalletLinkAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/receipts/$messageId/read': {
      id: '/api/v1/receipts/$messageId/read'
      path: '/read'
      fullPath: '/api/v1/receipts/$messageId/read'
      preLoaderRoute: typeof ApiV1ReceiptsMessageIdReadRouteImport
      parentRoute: typeof ApiV1ReceiptsMessageIdRoute
    }
    '/api/v1/postage/$messageId/settle': {
      id: '/api/v1/postage/$messageId/settle'
      path: '/settle'
      fullPath: '/api/v1/postage/$messageId/settle'
      preLoaderRoute: typeof ApiV1PostageMessageIdSettleRouteImport
      parentRoute: typeof ApiV1PostageMessageIdRoute
    }
    '/api/v1/postage/$messageId/refund': {
      id: '/api/v1/postage/$messageId/refund'
      path: '/refund'
      fullPath: '/api/v1/postage/$messageId/refund'
      preLoaderRoute: typeof ApiV1PostageMessageIdRefundRouteImport
      parentRoute: typeof ApiV1PostageMessageIdRoute
    }
    '/api/v1/policies/$owner/reconciliation': {
      id: '/api/v1/policies/$owner/reconciliation'
      path: '/reconciliation'
      fullPath: '/api/v1/policies/$owner/reconciliation'
      preLoaderRoute: typeof ApiV1PoliciesOwnerReconciliationRouteImport
      parentRoute: typeof ApiV1PoliciesOwnerRoute
    }
    '/api/v1/policies/$owner/provision': {
      id: '/api/v1/policies/$owner/provision'
      path: '/provision'
      fullPath: '/api/v1/policies/$owner/provision'
      preLoaderRoute: typeof ApiV1PoliciesOwnerProvisionRouteImport
      parentRoute: typeof ApiV1PoliciesOwnerRoute
    }
    '/api/v1/policies/$owner/senders/$sender': {
      id: '/api/v1/policies/$owner/senders/$sender'
      path: '/senders/$sender'
      fullPath: '/api/v1/policies/$owner/senders/$sender'
      preLoaderRoute: typeof ApiV1PoliciesOwnerSendersSenderRouteImport
      parentRoute: typeof ApiV1PoliciesOwnerRoute
    }
  }
}

interface ApiV1PoliciesOwnerRouteChildren {
  ApiV1PoliciesOwnerProvisionRoute: typeof ApiV1PoliciesOwnerProvisionRoute
  ApiV1PoliciesOwnerReconciliationRoute: typeof ApiV1PoliciesOwnerReconciliationRoute
  ApiV1PoliciesOwnerSendersSenderRoute: typeof ApiV1PoliciesOwnerSendersSenderRoute
}

const ApiV1PoliciesOwnerRouteChildren: ApiV1PoliciesOwnerRouteChildren = {
  ApiV1PoliciesOwnerProvisionRoute: ApiV1PoliciesOwnerProvisionRoute,
  ApiV1PoliciesOwnerReconciliationRoute: ApiV1PoliciesOwnerReconciliationRoute,
  ApiV1PoliciesOwnerSendersSenderRoute: ApiV1PoliciesOwnerSendersSenderRoute,
}

const ApiV1PoliciesOwnerRouteWithChildren =
  ApiV1PoliciesOwnerRoute._addFileChildren(ApiV1PoliciesOwnerRouteChildren)

interface ApiV1PostageMessageIdRouteChildren {
  ApiV1PostageMessageIdRefundRoute: typeof ApiV1PostageMessageIdRefundRoute
  ApiV1PostageMessageIdSettleRoute: typeof ApiV1PostageMessageIdSettleRoute
}

const ApiV1PostageMessageIdRouteChildren: ApiV1PostageMessageIdRouteChildren = {
  ApiV1PostageMessageIdRefundRoute: ApiV1PostageMessageIdRefundRoute,
  ApiV1PostageMessageIdSettleRoute: ApiV1PostageMessageIdSettleRoute,
}

const ApiV1PostageMessageIdRouteWithChildren =
  ApiV1PostageMessageIdRoute._addFileChildren(
    ApiV1PostageMessageIdRouteChildren,
  )

interface ApiV1ReceiptsMessageIdRouteChildren {
  ApiV1ReceiptsMessageIdReadRoute: typeof ApiV1ReceiptsMessageIdReadRoute
}

const ApiV1ReceiptsMessageIdRouteChildren: ApiV1ReceiptsMessageIdRouteChildren =
  {
    ApiV1ReceiptsMessageIdReadRoute: ApiV1ReceiptsMessageIdReadRoute,
  }

const ApiV1ReceiptsMessageIdRouteWithChildren =
  ApiV1ReceiptsMessageIdRoute._addFileChildren(
    ApiV1ReceiptsMessageIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolicyEditorRouteRoute: PolicyEditorRouteRoute,
  MotionGalleryRoute: MotionGalleryRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1ProtocolRoute: ApiV1ProtocolRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthLogoutAllRoute: ApiV1AuthLogoutAllRoute,
  ApiV1AuthRegisterRoute: ApiV1AuthRegisterRoute,
  ApiV1AuthSessionRoute: ApiV1AuthSessionRoute,
  ApiV1PoliciesOwnerRoute: ApiV1PoliciesOwnerRouteWithChildren,
  ApiV1PoliciesEvaluateRoute: ApiV1PoliciesEvaluateRoute,
  ApiV1PostageMessageIdRoute: ApiV1PostageMessageIdRouteWithChildren,
  ApiV1PostageQuoteRoute: ApiV1PostageQuoteRoute,
  ApiV1ReceiptsMessageIdRoute: ApiV1ReceiptsMessageIdRouteWithChildren,
  ApiV1RelayHealthRoute: ApiV1RelayHealthRoute,
  ApiV1RelayMessagesRoute: ApiV1RelayMessagesRoute,
  ApiV1RelayReadinessRoute: ApiV1RelayReadinessRoute,
  ApiV1RelayVersionRoute: ApiV1RelayVersionRoute,
  ApiV1MailboxSyncRoute: ApiV1MailboxSyncRoute,
  ApiV1PostageIndexRoute: ApiV1PostageIndexRoute,
  ApiV1ReceiptsIndexRoute: ApiV1ReceiptsIndexRoute,
  ApiV1WalletLinkAddressRoute: ApiV1WalletLinkAddressRoute,
  ApiV1WalletLinkChallengeRoute: ApiV1WalletLinkChallengeRoute,
  ApiV1WalletLinkVerifyRoute: ApiV1WalletLinkVerifyRoute,
  ApiV1WalletLinkIndexRoute: ApiV1WalletLinkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
